### ISSUE TITLE
mask expiry

### ISSUE THREAD

**Issue by jesopo** [Libera-Chat/bismite#1]
I've got a rough idea for how to express this:

```
<jess> addmask /^jesstest!/ +1d $spam
```

but the question is: one day *from when*? syn masks are an absolute expiry, so it would mean "one day from this moment", but those never really made sense. something better might be "one day from the last time this mask catches something".

another note to be made is maybe what we want the "expiry" to be is "time until downgrade" - thus, after a day, it would downgrade from `LETHAL` to `WARN`, and then after another day it would downgrade from `WARN` to disabled.

**Comment by ncoevoet** [comment]
i like the downgrade aspect of it, good idea

**Comment by examknow** [comment]
Probably wouldn’t be hard to implement either of those things. One question though is how often would we want to check for expired masks? My first instinct is to check every time we get a PONG from the server but maybe that’s too often?

**Comment by examknow** [comment]
I just realized it would make so much more sense to just use a timer!

**Comment by jesopo** [comment]
I'm interested in how you'd do that without leaving timers hanging around if a mask has already been toggled. my idea was loop every second and check for expired things
