### ISSUE TITLE
setmask's MaskType validation is inverted

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [Libera-Chat/bismite#56]
https://github.com/Libera-Chat/bismite/blob/main/bismite/__init__.py#L490-L491

```py
        elif args[1].upper() in MaskType:
            return [f"unknown mask type {args[1].upper()}"]
```
"if the mask exists in MaskType, tell the user the mask type is invalid"

This should be a `not in` and the contains check should be double checked.

**Comment by jesopo** [comment]
it also turns out `MaskType`'s `__contains__` override never worked
