### ISSUE TITLE
Store mask flags seperate from the actual mask pattern in database

### ISSUE THREAD

**Issue by examknow** [Libera-Chat/bismite#66]

**Comment by jesopo** [comment]
why?

**Comment by examknow** [comment]
For doing things like changing mask flags on the fly (as seen in #67), the only way we can do this is by taking the mask, taking out the flags, changing the flags, sticking the flags back on the pattern, and then putting that pattern into the database. It would be much less hacky if we just stored the flags in a separate column from the pattern.

**Comment by jesopo** [comment]
i'd prefer that changing mask flags be seen as synonymous with changing masks, and i'd prefer we have a way to add new masks and disable old ones
